---
openapi: 3.1.0
paths:
  /rest/api/v1/ticket:
    get:
      operationId: getTickets
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
      summary: Get Tickets
      tags:
      - Ticket Manager Resource
    post:
      operationId: createTicket
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ticket"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
      summary: Create Ticket
      tags:
      - Ticket Manager Resource
  /rest/api/v1/ticket/{ticketId}:
    get:
      operationId: getTicketById
      parameters:
      - name: ticketId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
      summary: Get Ticket
      tags:
      - Ticket Manager Resource
  /rest/api/v1/ticket/{ticketId}/transition/{status}:
    post:
      operationId: transitionTicket
      parameters:
      - name: status
        in: path
        required: true
        schema:
          type: string
      - name: ticketId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
      summary: Transition Ticket
      tags:
      - Ticket Manager Resource
components:
  schemas:
    Ticket:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        labels:
          type: array
          items:
            type: string
        project:
          type: string
        summary:
          type: string
        status:
          type: string
info:
  title: ticket-manager API
  version: 1.0.0
